### PR TITLE
New method "BytesToPrivateKey"

### PR DESCRIPTION
**Pull request by artjoma**
New method "BytesToPrivateKey"

### CODE REVIEW

**Comment by dchest** [comment]
I think it would make more sense to change `Sign` method to accept `rand io.Reader`, and get message randomization parameter from it. Then `PrivateKey` can be saved by storing `B`, which is already public (maybe it needs a better name).

**Comment by artjoma** [comment]
The idea of method "BytesToPrivateKey" was to restore PrivateKey object from bytes slice. It should be cool if Scheme will have this mechanism.

**Comment by dchest** [comment]
I understand. But since we don't need `r` to be stored in the private key, it can as well be generated during signing. If that was the case, you could already store private key by serializing it somehow (for example, using `gob`).

**Comment by artjoma** [comment]
Understand. I will apply next patch without restoring message digest randomization

**Comment by dchest** [comment]
Good idea for passing random reader to NewScheme. I simplified API to just have PrivateKey and PublicKey types that are just []byte, so BytesToPrivateKey is no longer needed. The Go standard library API, which I tried to emulate, always felt awkward. Please take a look: https://github.com/dchest/wots/pull/2

**Pull request closed without merging**
